name: Java CI

# Trigger this workflow on any push or pull request on the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Temurin distribution) - you specified Java 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '22'

      # Step 3: Build and package the application with Maven
      - name: Build with Maven
        run: mvn clean install
